import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider"; // ✅ correct import path

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
                <body>
                            <script
                              dangerouslySetInnerHTML={{
                                __html: `
                                  if (typeof window !== 'undefined') {
                                    Object.defineProperty(window, 'ethereum', {
                                      value: undefined,
                                      writable: false,
                                      configurable: false,
                                    });
                                  }
                                `,
                              }}
                            />                  <Provider>{children}</Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}